[package]
name = "rustmal"
version = "0.1.0"
authors = ["yskaksk <yskaksk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"
regex = "1.5.4"
once_cell = "1.8.0"
